# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d14734c596ca18524c0069ef09fa11de"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Tulola Sync"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
